<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Component\Validator\Constraints\Collection;

/**
 * GoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodsRepository extends EntityRepository
{
    public function showByPricesTypeAction($pricesType)
    {
        return $this->getEntityManager()->createQuery('SELECT p1.title,p1.description,p3.basename FROm AppBundle:Goods p1 JOIN AppBundle:Prices p2 WITH p1.id=p2.goodsId
                                                                                                                   JOIN AppBundle:Photo p3 WITH p2.goodsId=p3.goodsId
                                                                                                                   WHERE p2.priceTypeId=:price_type')->setParameter('price_type',$priceType)->getResult(Query::HYDRATE_OBJECT);
    }
}
